### ISSUE TITLE
Question on how to..

### ISSUE THREAD

**Issue by jackflem1** [corinuss/Hubitat_IntelliFire#2]
I'm trying to automate so that when I turn on the fireplace via Hubitat I can also set the Fan speed, Light level and flame height.
Via rule machine I can set the fan speed but can't figure out how to set the Light and flame?

**Comment by corinuss** [comment]
If doing this via Rule Machine, I think you'll need to use a "Run Custom Action" action for these.

For the initial "Capability of action device" field, set any capability that the device has (such as "Temperature").  This is just a filter for selecting a device, and has no effect on operation.
For light: "setLightLevel" with a number from 0 to 3.
For flame level: "setFlameHeight" with a number from 0 to 4.  (0 might actually turn it off.)

In Hubitat, Light and Switch capabilities share the same activation interface, so it's impossible to have both capabilities on the same device controlling different features, which is frustrating.  Also, my fireplace does not have a light, so this feature is untested by me, but it should work...

And I didn't see a Hubitat capability that was a good fit for Flame Height, though I tend to never adjust this anyways.

**Comment by jackflem1** [comment]
Worked perfectly. Thanks for the help!Thanks.JackOn Sep 22, 2023, at 12:04 PM, corinuss ***@***.***> wrote:﻿
If doing this via Rule Machine, I think you'll need to use a "Run Custom Action" action for these.
For the initial "Capability of action device" field, set any capability that the device has (such as "Temperature").  This is just a filter for selecting a device, and has no effect on operation.
For light: "setLightLevel" with a number from 0 to 3.
For flame level: "setFlameHeight" with a number from 0 to 4.  (0 might actually turn it off.)
In Hubitat, Light and Switch capabilities share the same activation interface, so it's impossible to have both capabilities on the same device controlling different features, which is frustrating.  Also, my fireplace does not have a light, so this feature is untested by me, but it should work...
And I didn't see a Hubitat capability that was a good fit for Flame Height, though I tend to never adjust this anyways.
