### ISSUE TITLE
Debug Logging Level set to Off, still logging

### ISSUE THREAD

**Issue by jackflem1** [corinuss/Hubitat_IntelliFire#4]
Updated to V2.0 code. turning off debug logging does not seem to work?

I commented out line 732  //log.debug "$pollDataMap"   which stopped it.

**Comment by jackflem1** [comment]
Code v2.1 corrected it

**Comment by corinuss** [comment]
Yeah, the debug messages were actually intentional at 2.0 launch, since it more clearly shows activity, are not pure dev debug messages, and can be filtered by Hubitat's log categories.  But I can see how it can be confusing/annoying, so they've been downgraded.
