### ISSUE TITLE
Getting repeated Fan Message v2.0.1 code

### ISSUE THREAD

**Issue by jackflem1** [corinuss/Hubitat_IntelliFire#5]
Getting repeated Fan Message code level 2.0.1.

[dev:224](http://192.168.86.13/logs#)2024-01-21 09:03:17.285 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 09:00:44.381 AM[info](http://192.168.86.13/logs#)Decreasing refresh frequency to every 15 minutes while fireplace is off.
[dev:224](http://192.168.86.13/logs#)2024-01-21 09:00:44.376 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 09:00:36.624 AM[info](http://192.168.86.13/logs#)Sending local command 'power = 0'
[dev:225](http://192.168.86.13/logs#)2024-01-21 09:00:36.438 AM[info](http://192.168.86.13/logs#)Intellifire was turned off
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:55:50.232 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:53:17.287 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:50:50.290 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:49:18.366 AM[info](http://192.168.86.13/logs#)Increasing refresh frequency to every 5 minutes while fireplace is on.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:49:18.361 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:49:11.033 AM[info](http://192.168.86.13/logs#)Sending local command 'flame_height = 4'
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:49:04.237 AM[info](http://192.168.86.13/logs#)Increasing refresh frequency to every 5 minutes while fireplace is on.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:49:04.233 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:49:00.588 AM[info](http://192.168.86.13/logs#)Sending local command 'light = 3'
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:53.714 AM[info](http://192.168.86.13/logs#)Increasing refresh frequency to every 5 minutes while fireplace is on.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:53.710 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:50.108 AM[info](http://192.168.86.13/logs#)Sending local command 'fan_speed = 1'
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:36.324 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:27.668 AM[info](http://192.168.86.13/logs#)Increasing refresh frequency to every 5 minutes while fireplace is on.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:27.663 AM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 08:48:19.996 AM[info](http://192.168.86.13/logs#)Sending local command 'power = 1'
[dev:225](http://192.168.86.13/logs#)2024-01-21 08:48:19.920 AM[info](http://192.168.86.13/logs#)Intellifire was turned on

**Comment by corinuss** [comment]
Is your fan actually running?

That's your fireplace reporting that error, though I'll look at adjusting the reporting so that it only logs if the error state changes.

**Comment by jackflem1** [comment]
No the fireplace is off (fan not running)  and still logging

[dev:224](http://192.168.86.13/logs#)2024-01-21 12:56:31.272 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:239](http://192.168.86.13/logs#)2024-01-21 12:55:17.971 PM[info](http://192.168.86.13/logs#)Shed is off [digital]
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:53:17.260 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:43:17.261 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:41:31.289 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:33:17.236 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:26:31.309 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:23:17.260 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:13:17.250 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:11:31.276 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.
[dev:224](http://192.168.86.13/logs#)2024-01-21 12:03:17.285 PM[error](http://192.168.86.13/logs#)Fireplace message: Fan Information: Fan will turn on within 3 minutes. Your appliance has a built-in delay that prevents the fan from operating within the first 3 minutes of turning on the appliance. This allows the air to be heated prior to circulation.

**Comment by corinuss** [comment]
Turn on debug spam and look at the status updates from the fireplace.  (You can hit Refresh to force a status update.)  In that block, you should see an "errors" field.  Does it list any numbers in that field (I think it should be reporting '[6]') or is it empty (showing '[]')?

**Comment by jackflem1** [comment]
It showing 6 for error


Thanks
Jack

**Comment by jackflem1** [comment]
I powered off and on the fireplace, did refresh and error is cleared


Thanks
Jack

**Comment by corinuss** [comment]
Ok, sounds like the code is working properly then, except for repeating the error message in the log.  I'll get that last part fixed.

FWIW, the Intellifire mobile app would have shown that error message too.  Odd that it didn't auto clear after 3 minutes, but that's a fireplace/module issue.  :/

**Comment by jackflem1** [comment]
I think what may have happened is the fireplace was on (fan on) and I shut
it off and turned it back on within a couple of minutes so the fan was
still running which may have put it in a weird state.
I have had very solid performance using local control with your code, I
modify the refresh to 10 minutes when on and 3 hours when off.


Thanks
Jack

**Comment by corinuss** [comment]
Sorry for the delay on this fix.  Life + dead WiFi module + more life = unable to fix issues.
But 2.1.0 should resolve this spam.  Now will only message when the error is initially hit (and will message on clear only if one of the Debug modes are set).

**Comment by corinuss** [comment]
Also, I highly recommend trying out the cloud polling.  Immediate response on status updates and doesn't have any of the stability issues that local polling does.
